print("1.*Loops are great*")
print("1.**Loops are great**")
print("1.***Loops are great***")
print("1.****Loops are great****")
print("1.*****Loops are great*****")
print("1.******Loops are great******")
